### ISSUE TITLE
APK crashes after custom build

### ISSUE THREAD

**Issue by tapir** [bjornbytes/lovr#350]
After successfully building the lovr.apk with my own setup I started to get a crash with the error below (I don't get this with the official lovr.apk)

```bash
12-14 22:03:57.163  5727  5727 E AndroidRuntime: Process: org.tapirvr.app, PID: 5727
12-14 22:03:57.163  5727  5727 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.tapirvr.app/org.tapirvr.app.Activity}: java.lang.ClassNotFoundException: Didn't find class "org.tapirvr.app.Activity" on path: DexPathList[[zip file "/data/app/org.tapirvr.app-jiQ7jpnTIyFFryIJnPhQlg==/base.apk"],nativeLibraryDirectories=[/data/app/org.tapirvr.app-jiQ7jpnTIyFFryIJnPhQlg==/lib/arm64, /data/app/org.tapirvr.app-jiQ7jpnTIyFFryIJnPhQlg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3203)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3418)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2025)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7387)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
12-14 22:03:57.163  5727  5727 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.tapirvr.app.Activity" on path: DexPathList[[zip file "/data/app/org.tapirvr.app-jiQ7jpnTIyFFryIJnPhQlg==/base.apk"],nativeLibraryDirectories=[/data/app/org.tapirvr.app-jiQ7jpnTIyFFryIJnPhQlg==/lib/arm64, /data/app/org.tapirvr.app-jiQ7jpnTIyFFryIJnPhQlg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at android.app.Instrumentation.newActivity(Instrumentation.java:1250)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3191)
12-14 22:03:57.163  5727  5727 E AndroidRuntime:        ... 11 more
12-14 22:03:57.173  1016  1052 E libprocessgroup: set_timerslack_ns write failed: No such process
12-14 22:03:57.212  1935  1935 E OVRMediaServiceManager: LivestreamingManager Not initialized
12-14 22:03:57.385  5505  5541 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
12-14 22:03:58.098  1935  1935 E OVRMediaServiceManager: LivestreamingManager Not initialized
12-14 22:03:58.126  2660  2733 E PersistableBundle: Failed at frameworks/native/libs/binder/PersistableBundle.cpp:158 (erase)
12-14 22:03:58.170  5757  5757 E ll.home:explor: Not starting debugger since process cannot load the jdwp agent.
12-14 22:03:58.201  5757  5757 E LoadedApk: Unable to instantiate appComponentFactory
12-14 22:03:58.201  5757  5757 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/app/VrHome/VrHome.apk"],nativeLibraryDirectories=[/system/app/VrHome/lib/arm, /system/fake-libs, /system/app/VrHome/VrHome.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib, /system/lib, /system/product/lib]]
12-14 22:03:58.201  5757  5757 E LoadedApk:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at android.app.LoadedApk.createAppFactory(LoadedApk.java:256)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:859)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at android.app.LoadedApk.getClassLoader(LoadedApk.java:954)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at android.app.LoadedApk.getResources(LoadedApk.java:1192)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at android.app.ContextImpl.createAppContext(ContextImpl.java:2474)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at android.app.ContextImpl.createAppContext(ContextImpl.java:2466)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6368)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at android.app.ActivityThread.access$1300(ActivityThread.java:226)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1868)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at android.os.Handler.dispatchMessage(Handler.java:107)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at android.os.Looper.loop(Looper.java:214)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at android.app.ActivityThread.main(ActivityThread.java:7387)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at java.lang.reflect.Method.invoke(Native Method)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-14 22:03:58.201  5757  5757 E LoadedApk:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

~~Looks like a common build issue and the recommendation is to add `android.enableR8=false` to gradle build files however I can't seem to locate one (probably cmake creates some intermediary ones?)~~

Would appreciate any pointers
Thanks

**Update:** I actually put the wrong error message. Updated.

**Comment by bjornbytes** [comment]
Ok this error makes more sense.

If you want to change the package ID to something other than org.lovr.app, it needs to be done in a couple of places:

- Activity Java files (`package org.lovr.app;`)
- Android Manifest XML files (`package="org.lovr.app"`)
- Build system path to .class file (`org/lovr/app/Activity.class`)

We are working on documenting this and making it easier (#342), but I think changing those 3 places should fix the ClassNotFound exception.

**Comment by tapir** [comment]
Makes sense. I'm almost sure that I also tried with the default manifest file (without changing bundle id) but I'll double check.

**Comment by tapir** [comment]
And here is the error I get when trying to run the APK with the default manifest file from the repo

```
12-15 18:39:45.442  9106  9106 E org.lovr.app: Not starting debugger since process cannot load the jdwp agent.
12-15 18:39:45.478  9106  9106 E AndroidRuntime: FATAL EXCEPTION: main
12-15 18:39:45.478  9106  9106 E AndroidRuntime: Process: org.lovr.app, PID: 9106
12-15 18:39:45.478  9106  9106 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.lovr.app-2zV8H14mH6HBGlKtp-VDBg==/base.apk"],nativeLibraryDirectories=[/data/app/org.lovr.app-2zV8H14mH6HBGlKtp-VDBg==/lib/arm64, /data/app/org.lovr.app-2zV8H14mH6HBGlKtp-VDBg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblovr.so"
```

So it can't find the `liblovr.so` file. At this point I'm pretty it's my fault, just can't figure out what.

**Comment by bjornbytes** [comment]
You can do `aapt list lovr.apk` to see what files are in the apk (or just unzip it).  There should be `lib/arm64-v8a/liblovr.so` in there.  Someone else was having an issue with missing libraries and it was fixed by rerunning CMake, maybe this is the same problem.

**Comment by tapir** [comment]
I use `cmake .. && cmake --build .` to build the APK file. I don't use `tup` (if that makes any difference?)

I've checked the build directory and indeed all the necessary files are there:
![Untitled2](https://user-images.githubusercontent.com/223984/102268546-c1061400-3f1b-11eb-8cec-40a71256a427.jpg)
However when I look inside the built APK file I only see `libvrapi.so`
![Untitled](https://user-images.githubusercontent.com/223984/102268598-d24f2080-3f1b-11eb-9004-8fd7e7cb5e6f.jpg)

**Comment by bjornbytes** [comment]
Ok, this is the exact same problem somebody else was having (only libvrapi ending up in the APK).  They said

> I deleted the lovr.apk and then built again
> I can see the .so files added this time in the apk, so I guess it was a timing thing

**Comment by bjornbytes** [comment]
I think `add_dependencies(buildAPK lovr)` needs to be added to CMakeLists to get things to run in the correct order, going to see if this fixes it

**Comment by tapir** [comment]
It worked! So the first build from scratch doesn't include all the files. The second build however successfully puts everything in the apk file.
I think it's an ordering issue indeed.

**Comment by bjornbytes** [comment]
Added `add_dependencies` to cause things to build in the correct order
