### ISSUE TITLE
Setting t.graphics.debug to true emits VK_ERROR_LAYER_NOT_PRESENT

### ISSUE THREAD

**Issue by lun-4** [bjornbytes/lovr#598]
I was finding this issue while porting one of my projects to 0.16, and I nailed it down to `t.graphics.debug = true`. It's possible this problem is related to my graphics drivers on my mobile GPU (GeForce MX350), but I need some help to nail down this problem. Setting it back to `false` works.

# Reproduction steps:

## main.lua

```lua
function lovr.draw(pass)
    pass:text('hello world', 0, 1.7, -5)
end
```

## conf.lua

```lua
function lovr.conf(t)
    t.graphics.debug = true
end
```

## Result

```
Error:
GPU error: Vulkan error: VK_ERROR_LAYER_NOT_PRESENT

Stack:
boot.lua:90: in function <boot.lua:4>
[C]: in function 'xpcall'
fish: Job 1, '~/other.git/lovr/build/bin/lovr…' terminated by signal SIGSEGV (Address boundary error)
```

# vulkaninfo reported layers

```
Layers: count = 5
=================
VK_LAYER_NV_optimus (NVIDIA Optimus layer) Vulkan version 1.3.205, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 1
		GPU id = 0 (NVIDIA GeForce MX350)
		Layer-Device Extensions: count = 0

VK_LAYER_VALVE_steam_fossilize_32 (Steam Pipeline Caching Layer) Vulkan version 1.3.207, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 1
		GPU id = 0 (NVIDIA GeForce MX350)
		Layer-Device Extensions: count = 0

VK_LAYER_VALVE_steam_fossilize_64 (Steam Pipeline Caching Layer) Vulkan version 1.3.207, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 1
		GPU id = 0 (NVIDIA GeForce MX350)
		Layer-Device Extensions: count = 0

VK_LAYER_VALVE_steam_overlay_32 (Steam Overlay Layer) Vulkan version 1.3.207, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 1
		GPU id = 0 (NVIDIA GeForce MX350)
		Layer-Device Extensions: count = 0

VK_LAYER_VALVE_steam_overlay_64 (Steam Overlay Layer) Vulkan version 1.3.207, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 1
		GPU id = 0 (NVIDIA GeForce MX350)
		Layer-Device Extensions: count = 0
```

# gdb backtrace

Made by self building lovr with `cmake -DCMAKE_BUILD_TYPE=Debug ..`, but this is reproducible in Release mode as well. From what I understand it crashes because it's printing out the stack trace of the GPU error, but it doesn't have a GPU available due to to aforementioned error.

```
#0  0x0000000000000000 in ?? ()
#1  0x000055555588f17a in gpu_wait_tick (tick=4294967293) at lovr/src/core/gpu_vk.c:2432
#2  0x000055555588eca4 in gpu_begin () at lovr/src/core/gpu_vk.c:2367
#3  0x000055555586eeb0 in beginFrame () at lovr/src/modules/graphics/graphics.c:5481
#4  0x000055555585f9f7 in lovrFontGetLines (font=0x555555e60a90, strings=0x7ffffffeced0, count=1, wrap=26.9696026, callback=0x55555587b169 <online>,
    context=0x7ffff7af8a58) at lovr/src/modules/graphics/graphics.c:2376
#5  0x000055555587b28c in l_lovrFontGetLines (L=0x7ffff7af8a58) at lovr/src/api/l_graphics_font.c:127
#6  0x00007ffff7f3b025 in lj_BC_FUNCC () at buildvm_x86.dasc:849
#7  0x00007ffff7ef0dd9 in lj_err_run (L=0x7ffff7af8a58) at lovr/deps/luajit/src/lj_err.c:617
#8  0x00007ffff7ef19ff in lua_error (L=0x7ffff7af8a58) at lovr/deps/luajit/src/lj_err.c:817
#9  0x00005555557bc4bb in luax_vthrow (context=0x7ffff7af8a58, format=0x555555ae4ac8 "GPU error: %s", args=0x7ffffffed0d0) at lovr/src/api/api.c:298
#10 0x00005555557bd6a0 in lovrThrow (format=0x555555ae4ac8 "GPU error: %s") at lovr/src/util.c:18
#11 0x0000555555870ff3 in onMessage (context=0x0, message=0x555555ae7d90 "Vulkan error: VK_ERROR_LAYER_NOT_PRESENT", severe=true) at lovr/src/modules/graphics/graphics.c:5892
#12 0x00005555558911c9 in vcheck (result=VK_ERROR_LAYER_NOT_PRESENT, message=0x555555ae7003 "Instance creation failed") at lovr/src/core/gpu_vk.c:2929
#13 0x000055555588baa9 in gpu_init (config=0x7fffffffdf10) at lovr/src/core/gpu_vk.c:1853
#14 0x00005555558573e3 in lovrGraphicsInit (config=0x7fffffffe190) at lovr/src/modules/graphics/graphics.c:471
#15 0x0000555555872bf8 in l_lovrGraphicsInitialize (L=0x7ffff7af8a58) at lovr/src/api/l_graphics.c:671
#16 0x00007ffff7f3b025 in lj_BC_FUNCC () at buildvm_x86.dasc:849
#17 0x00007ffff7eb70d4 in lua_resume (L=0x7ffff7af8a58, nargs=0) at lovr/deps/luajit/src/lj_api.c:1266
```

**Comment by bjornbytes** [comment]
Ok error screen prints the error if graphics is unavailable, and Vulkan renderer checks for all layers/extensions before enabling, warning/falling back if debug stuff isn't available.
